### PR TITLE
1700

### PR DESCRIPTION
**Pull request by ghost**
THEY ARE VERY EAGER TO LEARN

### CODE REVIEW

**Comment by Fexcraft** [comment]
Are you a bot? 🤔

**Comment by ghost** [comment]
No ,Iam only trying to learn how to use this

**Comment by Fexcraft** [comment]
Hmm, you mean how to use GitHub or how to use FCL?

As you are creating "pull requests", to merge the code you "edited" with the FCL main repository, although your edits are not by any means relevant or anything useful to FCL.

**Comment by ghost** [comment]
>           Hmm, you mean how to use GitHub or how to use FCL?
> As you are creating "pull requests", to merge the code you "edited" with the FCL main repository, although your edits are not by any means relevant or anything to FCL.

Sorry .

**Comment by Fexcraft** [comment]
Oh, I see you have in your profile picture something that shortened also is called "FCL".
But it doesn't seem to have anything in common with ***my*** FCL, this is a Library with useful code for my **Minecraft** Mods.

Is this by accident or you need anything from **F**excraft **C**ommon **L**ibrary?

**Comment by ghost** [comment]
Learning this tool is a part of educational training.

**Comment by Fexcraft** [comment]
What do you call `tool`, Github or https://github.com/Fexcraft/FCL?

**Comment by ghost** [comment]
Only Github
FCL means Future class learning

**Comment by Fexcraft** [comment]
Hmm, I see.
You should maybe read some guides/tutorials on Github first or such.

This repository is **FCL** - **Fexcraft Common Library,**
if you want to have a repository with the same name (ID - FCL),
delete the your fork of this repository and create a **new** repository instead.

Else things will work wrong, as your project has no relation to this one, only the short-name is same.

**Comment by Fexcraft** [comment]
Closed, as the other user is apparently _deleted_.

**Pull request closed without merging**
